### PR TITLE
Fix duplicated exported content with memory export

### LINKED ISSUE #391: In Memory Export function results in duplicated codelabs content
To repro: change the fetcher in the Codelab Export to MemoryFetcher, and use that to slurp out the codelab. You'll see that the thing put into the output buffer contains (generated content) * (number of codelab.Step).

### PR DESCRIPTION
**Pull request by KeyboardNerd**
Fixes #391

### CODE REVIEW

File: claat/cmd/export_test.go [hunk 1]
```diff
@@ -41,7 +42,6 @@ func TestExportCodelabMemory(t *testing.T) {
 		{
 			name:     "Multiple Steps",
 			filePath: "testdata/simple-2-steps.md",
-			knownBug: "https://github.com/googlecodelabs/tools/issues/391",
```
Comment (shawnbuso) [inline claat/cmd/export_test.go]: Can we remove the test.knownBug check below now?

File: claat/cmd/export.go [hunk 2]
```diff
@@ -169,6 +169,16 @@ func writeCodelabWriter(w io.Writer, clab *types.Codelab, extraVars map[string]s
 		Steps:    clab.Steps,
 		Extra:    extraVars,
 	}}
+
+	if ctx.Format != "offline" {
+		ext := ctx.Format
```
Comment (shawnbuso) [inline claat/cmd/export.go]: Does this end up getting used somewhere? Do we need the intermediate variable?

File: claat/cmd/export.go [hunk 3]
```diff
@@ -169,6 +169,16 @@ func writeCodelabWriter(w io.Writer, clab *types.Codelab, extraVars map[string]s
 		Steps:    clab.Steps,
 		Extra:    extraVars,
 	}}
+
+	if ctx.Format != "offline" {
```
Comment (shawnbuso) [inline claat/cmd/export.go]: Does it make more sense to invert this? 

if ctx.Format == "offline"
  for loop
else
  stuff currently in conditional block

Comment (KeyboardNerd) [reply claat/cmd/export.go]: sure, either way is fine for me

File: claat/cmd/export.go (hunk 2 above)
Comment (KeyboardNerd) [reply claat/cmd/export.go]: I actually think we should remove the "offline" support for the Memory Export because  offline should require multiple io.Writer instead of one to make it work properly.

File: claat/cmd/export_test.go (hunk 1 above)
Comment (KeyboardNerd) [reply claat/cmd/export_test.go]: Removed.
